name: Deploy infra from terraform

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
      id-token: write
      contents: read
      pull-requests: write


jobs:
  Check_files_init_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4


      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.9.6
      
      - name: run fmt 
        id: fmt
        run: terraform fmt
      
      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

      - run: |
          ls -la
          pwd
          echo " "
      
      - name: Upload Artifact - Terraform files
        uses: actions/upload-artifact@v4
        with:
          name: terra-files
          path: terraform
          include-hidden-files: true

  Terraform_plan:
    needs: Check_files_init_backend
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact - Terraform files
        uses: actions/download-artifact@v4
        with:
          name: terra-files
          
      - run: |
          ls -la
          chmod -R +x .terraform/*

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Plan
        run: terraform plan



