name: Deploy infra from terraform

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
      id-token: write
      contents: read
      pull-requests: write


jobs:
  Connection_and_Pull_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with: 
          terraform_version: 1.9.6
  
  Terraform_fmt:
    needs: [Connection_and_Pull_repo]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        
      - name: run fmt 
        id: fmt
        run: terraform fmt -check
